-- 코드를 입력하세요

SELECT a.CAR_ID AS CAR_ID, ROUND(a.AVERAGE_DURATION, 1) AS AVERAGE_DURATION
FROM (SELECT CAR_ID, AVG(DATEDIFF(end_date, start_date) + 1) AS AVERAGE_DURATION
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        GROUP BY CAR_ID) a
WHERE TRUE
    AND AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC