SELECT ROUTE
     , concat(round(SUM(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE
     , concat(round(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
  FROM SUBWAY_DISTANCE 
 GROUP BY ROUTE
 ORDER BY CAST(REPLACE(TOTAL_DISTANCE, 'km', '') AS float) DESC