-- 코드를 입력하세요
SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME, DATE_FORMAT(BOOK.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK JOIN AUTHOR
ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
WHERE 1=1
    AND BOOK.CATEGORY = '경제'
ORDER BY BOOK.PUBLISHED_DATE ASC
;